Repository typescript-eslint/tslint-to-eslint-config, pull requests merged in 2020-06, with the labels that each got.

#601 improve type safety with regards to config files
  src/creation/eslint/createEnv.test.ts
  src/creation/eslint/createEnv.ts
  src/input/findESLintConfiguration.ts
  src/input/findOriginalConfigurations.ts
  src/input/findPackagesConfiguration.ts
  src/input/findReportedConfiguration.ts
  src/input/findTSLintConfiguration.ts
  src/input/findTypeScriptConfiguration.ts
  src/input/mergeLintConfigurations.ts
  src/rules/convertRules.test.ts
  src/rules/convertRules.ts
Labels: status: waiting for author

#615 Added jsx-boolean-value converter
  src/rules/converters/eslint-plugin-react/jsx-boolean-value.ts
  src/rules/converters/eslint-plugin-react/tests/jsx-boolean-value.test.ts
  src/rules/rulesConverters.ts
Labels: status: waiting for reviewer

#616 refactor: ban-ts-ignore converter to ban-ts-comment
  src/rules/converters/ban-ts-ignore.ts
  src/rules/converters/tests/ban-ts-ignore.test.ts
Labels: area: incomplete converter
