Repository typescript-eslint/tslint-to-eslint-config, pull requests merged in 2020-07, with the labels that each got.

#642 chore: add dependencies label on renovatebot PRs
  renovate.json
Labels: tooling

#644 Quote wildcards for shell command
  README.md
Labels: documentation

#648 fix: do not convert next-line to line for comments
  src/comments/convertFileComments.test.ts
  src/comments/replaceFileComments.ts
Labels: area: comment conversions, type: cleanup

#636 Added jsx-curly-spacing converter
  src/rules/converters/eslint-plugin-react/jsx-curly-spacing.ts
  src/rules/converters/eslint-plugin-react/tests/jsx-curly-spacing.test.ts
  src/rules/rulesConverters.ts
Labels: status: waiting for reviewer

#617 fix: converters now uses naming-convention
  src/rules/converters/class-name.ts
  src/rules/converters/interface-name.ts
  src/rules/converters/tests/class-name.test.ts
  src/rules/converters/tests/interface-name.test.ts
  src/rules/converters/tests/variable-name.test.ts
  src/rules/converters/variable-name.ts
Labels: status: waiting for reviewer

#650 Ignore all unknown editor settings in conversion
  src/editorSettings/convertEditorSettings.test.ts
  src/editorSettings/convertEditorSettings.ts
Labels: type: enhancement

#654 Add jsx-no-bind rule
  src/rules/converters/eslint-plugin-react/jsx-no-bind.ts
  src/rules/converters/eslint-plugin-react/tests/jsx-no-bind.test.ts
  src/rules/rulesConverters.ts
Labels: status: waiting for author
